### ISSUE TITLE
Error:Could not find pl.brightinventions:slf4android:0.0.11.

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [mklimek/frame-video-view#11]
Gradle Version 2.1.2
Added 
      compile "com.github.mklimek:frame-video-view:1.3.0" to module build.gradle
Added 
        maven { url "https://jitpack.io" } to project build.gradle

but Android Studio 2.1.2 throws the following error
Error:Could not find pl.brightinventions:slf4android:0.0.11.
Required by:
    App:app:unspecified
    App:app:unspecified > com.github.mklimek:frame-video-view:1.3.0
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by mklimek** [comment]
Version 1.3.0 uses [slf4android](https://github.com/bright/slf4android) 0.0.11 which is hosted in their own public repository you haven't added. 

I released 1.3.1 with most recent version of slf4android which is hosted on jitpack.io like FrameViedoView.
It should work for you.
