### ISSUE TITLE
compile 'com.github.mklimek:frame-video-view:1.3.1' not working

### ISSUE THREAD

**Issue by pituseligmann** [mklimek/frame-video-view#12]
Hi!
You said to get the release code from the releases tab, and last one is 1.3.1. When trying to add the line 

`compile 'com.github.mklimek:frame-video-view:1.3.1'`

I get

`Error:(32, 13) Failed to resolve: com.github.mklimek:frame-video-view:v1.3.1`

Any ideas? Thanks!

**Comment by mklimek** [comment]
From README:
```groovy
allprojects {
        repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
```
Have you got this?

**Comment by pituseligmann** [comment]
Ah, that was my mistake then. All solved, thanks!
