### ISSUE TITLE
FrameVideoViewListener must either be declared abstract or implement abstract method

### ISSUE THREAD

**Issue by pituseligmann** [mklimek/frame-video-view#13]
I'm trying to load a video using your library from within a ViewPager fragment. I'm pretty much following the same on the readme but I'm getting the error mentioned above while doing:

```java
FrameVideoView frameVideoView = (FrameVideoView) fragment.findViewById(R.id.frame_video_view);
            frameVideoView.setup(Uri.parse("android.resource://" + getActivity().getPackageName() + "/" + R.raw.playlist_2_video_1));
            frameVideoView.setFrameVideoViewListener(new FrameVideoViewListener() {
                @Override
                public void mediaPlayerPrepared(final MediaPlayer mediaPlayer) {
                    mediaPlayer.start();
                }
            });
```
This is just for testing, what I really want to be able to do is save a reference of mediaPlayer or something, so I can call mediaPlayer.start() when my fragment is visible to the user on a different method, but that's on me.

**Comment by mklimek** [comment]
You missed one method.
[This](https://github.com/mklimek/frame-video-view/blob/master/library/src/main/java/com/mklimek/frameviedoview/FrameVideoViewListener.java) in an interface to implement.
