### ISSUE TITLE
setup(URI) function is synchronise and very slow

### ISSUE THREAD

**Issue by itzharDev** [mklimek/frame-video-view#20]

**Comment by mklimek** [comment]
FrameVideoView is just a wrapper and does nothing with an internal android implementation like mentioned `setup()` method.

**Comment by itzharDev** [comment]
in my recyclerview, if I commented this line only, items just flow as well.
when I'm using the frame.setup(URI) - recycler get stack till MediaPlayer prepared.

if u have any advice
