### ISSUE TITLE
Release on texture surface destroyed

### ISSUE THREAD

**Issue by m-kubis** [mklimek/frame-video-view#8]
Hi, there is a re-initialization issue on surface destruction. For example when placing the video into the RecyclerView. The recycling of the view can be handled with #onResume()/#onPause() with the RecycleView#onBindViewHolder(...)/#onViewRecycled(...) callbacks. However the surface state change callbacks of the implementation are not accessible from the outside. The exact moment the texture view goes out of view (the last pixel scrolls out of the screen), TextureViewImpl#onSurfaceTextureDestroyed(Surface) gets called and the following onSurfaceTextureAvailable(Surface) doesn't initialize the media player due to not being released (and flag set).

The player should be released and the placeholder view shown. Simple doing #onResume() in TextureViewImpl#onSurfaceTextureDestroyed(Surface) should do the trick.
[Before](https://dl.dropboxusercontent.com/u/51084065/device-2016-06-02-142727.mp4)
[After releasing on surface destruction](https://dl.dropboxusercontent.com/u/51084065/device-2016-06-02-151538.mp4)

**Comment by mklimek** [comment]
Thanks for a feedback!
If you already solved it, can you create a pull request?

**Comment by m-kubis** [comment]
Ok, I did. The thing is I have no way to test the video view implementation for the issue. You might want to look at that.

**Comment by mklimek** [comment]
I think it's not a big deal because API Level 13 is running roughly 2% of all devices.
Thanks for a contribution 👍
